name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - name:  Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name:  Comment
        uses: peaceiris/actions-label-commenter@v1.8.2
        with:
          config_file: .github/label-comments.yaml